# Generated by Django 4.2 on 2023-05-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSIS', 'Bachelor of Science in Information Systems'), ('CompEng', 'Bachelor of Science in Computer Engineering'), ('ComScie', 'Bachelor of Science in Computer Science')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rank',
            name='faculty_rank',
            field=models.CharField(choices=[('Assoc Prof 1', 'Associate Professor I'), ('Assoc Prof 2', 'Associate Professor II'), ('Assoc Prof 3', 'Associate Professor III'), ('Prof 1', 'Professor I'), ('Prof 2', 'Professor II')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_title',
            field=models.CharField(choices=[('DSA 1', 'Data Structure and Algortihm'), ('SAD', 'System Analysis & Design'), ('Prog I', 'Introduction to Programming')], max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('Option 1', '2020'), ('Option 2', '2021'), ('Option 3', '2022'), ('Option 4', '2023'), ('Option 5', '2024'), ('Option 6', '2025')], max_length=50),
        ),
    ]
