# Generated by Django 4.2 on 2023-05-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_course_course_title_alter_rank_faculty_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseevaluation',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='courseevaluation',
            name='faculty_rank',
        ),
        migrations.RemoveField(
            model_name='courseevaluation',
            name='subject_title',
        ),
        migrations.RemoveField(
            model_name='courseevaluation',
            name='year',
        ),
    ]
