# Generated by Django 4.2 on 2023-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_course_delete_rank_delete_subject_delete_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevaluation',
            name='subject_title',
            field=models.CharField(choices=[('1', 'ENG 14-IT'), ('2', 'ELECTIVE 11'), ('3', 'SOC SCI 19-IT'), ('4', 'SOC SCI 12-IT'), ('5', 'IT 110-IT'), ('6', 'IT 111-IT'), ('7', 'ELECTIVE 12-IT'), ('8', 'PE 4-IT'), ('9', 'PROF ED 2-IT')], max_length=50),
        ),
    ]
