# Generated by Django 4.2 on 2023-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_courseevaluation_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevaluation',
            name='semester',
            field=models.CharField(choices=[('1', '1st semester'), ('2', '2nd semester'), ('3', 'Summer Class')], max_length=100),
        ),
    ]
