# Generated by Django 4.2 on 2023-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_courseevaluation_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevaluation',
            name='semester',
            field=models.CharField(choices=[('1st semester', '1st semester'), ('2nd semester', '2nd semester'), ('Summer Class', 'Summer Class')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courseevaluation',
            name='subject_title',
            field=models.CharField(choices=[('ENG 14-IT', 'ENG 14-IT'), ('ELECTIVE 11', 'ELECTIVE 11'), ('SOC SCI 19-IT', 'SOC SCI 19-IT'), ('SOC SCI 12-IT', 'SOC SCI 12-IT'), ('IT 110-IT', 'IT 110-IT'), ('IT 111-IT', 'IT 111-IT'), ('ELECTIVE 12-IT', 'ELECTIVE 12-IT'), ('PE 4-IT', 'PE 4-IT'), ('PROF ED 2-IT', 'PROF ED 2-IT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courseevaluation',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=50),
        ),
    ]
