# Generated by Django 4.2 on 2023-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_evaluator_courseevaluation_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseevaluation',
            name='subject_code',
            field=models.CharField(choices=[('CC 118', 'CC 118'), ('CC 119', 'CC 119'), ('CC 120', 'CC 120'), ('CC 121', 'CC 121'), ('CC 122', 'CC 122'), ('CC 123', 'CC 123'), ('TECHNO  11', 'TECHNO  11'), ('PROF ED 14', 'PROF ED 14')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseevaluation',
            name='subject_title',
            field=models.CharField(choices=[('Information Assurance and Security 1', 'Information Assurance and Security 1'), ('Social and Professional Issues', 'Social and Professional Issues'), ('Application Development and Emerging', 'Application Development and Emerging'), ('System Integration and Architecture 1', 'System Integration and Architecture 1'), ('System Integration and Architecture 1', 'System Integration and Architecture 1'), ('Capstone Project and Research 1', 'Capstone Project and Research 1'), ('Technopreneurship', 'Technopreneurship'), ('Assessment of Learning 1', 'Assessment of Learning 1')], max_length=50),
        ),
    ]
